FROM nginx

WORKDIR /usr/share/nginx/html

RUN rm -rf ./*

COPY ./index.html .

EXPOSE 80

# nginx -g daemon off;
CMD ["nginx","-g","daemon off;"]

# docker build -t site-perso:v1 .

# docker run -p 80:80 --name site site-perso:v1