# choisir une image de depart
FROM nginx

# modification de cette image de base

# je mme place dans un repertoire
WORKDIR /usr/share/nginx/html

# je supprime tous ce qui ce trouve dans ce repertoire
RUN rm -rf ./*

# installation de git
RUN apt update && apt install -y git

# utilisation de git pour recuperer mon projet
RUN git clone https://github.com/withaarzoo/3D-Rotate-Tube.git .

EXPOSE 80

CMD ["nginx","-g","daemon off;"]

# docker build -t exo6 .
# docker run -d -p 5000:80 exo6
