stages:
  - packaging

packaging-aws:
  stage: packaging
  image: 
    name: amazon/aws-cli
    entrypoint: [""]
  services:
    - docker:29-dind
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
  before_script:
    - yum install -y docker
    - export AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
    - export AWS_REGISTRY=${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com
    - aws ecr get-login-password --region ${AWS_DEFAULT_REGION} | docker login --username AWS --password-stdin ${AWS_REGISTRY}
  script:
    - docker build -t ${AWS_REGISTRY}/${AWS_ECR_IMAGE_NAME}:${CI_COMMIT_SHORT_SHA} .
    - docker push ${AWS_REGISTRY}/${AWS_ECR_IMAGE_NAME}:${CI_COMMIT_SHORT_SHA}