apiVersion: v1
kind: Service
metadata:
  name: front
  labels:
    app: front
    {{- include "stockline.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app: front
  ports:
    - name: http
      port: 80
      targetPort: 80
