apiVersion: apps/v1
kind: Deployment
metadata:
  name: front
  labels:
    app: front
    {{- include "stockline.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.front.replicas }}
  selector:
    matchLabels:
      app: front
  template:
    metadata:
      labels:
        app: front
        {{- include "stockline.labels" . | nindent 8 }}
    spec:
      containers:
        - name: front
          image: {{ include "stockline.frontImage" . | quote }}
          imagePullPolicy: {{ .Values.front.image.pullPolicy }}
          ports:
            - containerPort: 80
              name: http
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 2
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 10
          resources:
            {{- toYaml .Values.front.resources | nindent 12 }}
