apiVersion: v1
kind: Service
metadata:
  name: exo-07-japan-nginx-service
spec:
  type: LoadBalancer
  selector:
    app: exo-07-japan-nginx
    tier: backend
  ports:
    - port: 3000
      targetPort: 3000
