apiVersion: v1
kind: PersistentVolume
metadata:
  name: exo-09-pv
  namespace: exo-09-namespace
spec:
  capacity:
    storage: "10Gi"
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/postgres-data
    type: DirectoryOrCreate
