variables:
  DOCKER_CONTAINER_NAME: oubli-nom-pas-bien

stages:
  - build
  - test
  - packaging
  - deploy

build-app:
  stage: build
  image: node:26.9-alpine3.24
  script:
    - npm ci
    - npm run build
  artifacts:
    paths:
      - build/

unit-testing:
  dependencies: []
  image: node:26.9-alpine3.24
  stage: test
  script:
    - npm ci
    - npm run test
  artifacts:
    paths:
      - reports/html/
    reports:
      junit: reports/junit.xml

check-vulnerabilities:
  dependencies: []
  image: 
    name: aquasec/trivy:0.74.0
    entrypoint: [""]
  stage: test
  script:
    - trivy fs --severity HIGH,CRITICAL -f json -o dependencies-vulnerabilities.json .
  artifacts:
    paths:
      - dependencies-vulnerabilities.json

packaging-app:
  dependencies: []
  image: docker:29
  services:
    - docker:29-dind
  stage: packaging
  before_script:
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
  script:
    - docker build -t $CI_REGISTRY_IMAGE:latest -t $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA  .
    - docker push -a $CI_REGISTRY_IMAGE

## Variables à crééer sur Gitlab CI
# - EC2_USER: L'utilisateur utilisé par la machine virtuelle EC2 (par défaut 'ec2-user')
# - EC2_PUBLIC_IP: L'adresse IP publique de la machine virtuelle EC2, récupérée dans l'interface AWS Console
# - PRIVATE_KEY_B64: La clé privée .pem permettant de se connecter à la machine virtuelle EC2 (masked / hidden)
# - KNOWN_HOSTS_B64: Le contenu du fichier known_host permettant d'éviter la question de confirmation lors de la connexion du runner à l'instance (généré par la commande ssh-keyscan -H -t ssh-ed25519 $EC2_PUBLIC_IP)

.deploy-app:
  stage: deploy
  image: alpine:3.24.2
  before_script:
    - apk update
    - apk add openssh-client
    - mkdir -p ~/.ssh/
    - echo $PRIVATE_KEY_B64 | base64 -d > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - echo $KNOWN_HOSTS_B64 | base64 -d > ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
  script:
    - ssh -i ~/.ssh/id_rsa ${EC2_USER}@${EC2_PUBLIC_IP} "echo $CI_REGISTRY_PASSWORD | docker login $CI_REGISTRY -u $CI_REGISTRY_USER --password-stdin && docker pull $CI_REGISTRY_IMAGE:latest && docker stop $DOCKER_CONTAINER_NAME || true && docker rm $DOCKER_CONTAINER_NAME || true && docker run -d --name $DOCKER_CONTAINER_NAME --restart always -p 80:80 $CI_REGISTRY_IMAGE:latest"
