apiVersion: apps/v1
kind: Deployment
metadata:
  name: tasks-deployment
  namespace: exo-10-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tasks
  template:
    metadata:
      labels:
        app: tasks
    spec:
      volumes:
        - name: tasks-volume
          persistentVolumeClaim:
            claimName: exo-10-pvc
      containers:
        - name: tasks
          image: gharrowbm/kube-exo-10-tasks:latest
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "200m"
          volumeMounts:
            - name: tasks-volume
              mountPath: /app/tasks/
          envFrom:
            - configMapRef:
                name: auth-configmap
          env:
            - name: TASKS_FOLDER
              value: tasks
