apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-deployment
  namespace: exo-10-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
        - name: users
          image: gharrowbm/kube-exo-10-users:latest
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "200m"
          envFrom:
            - configMapRef:
                name: auth-configmap
